#!/usr/bin/perl
# vi: sw=3 ai sm:
# WARNING: THIS CODE DOES NOT WORK. DO NOT USE IT!!!

# usage: mrtg-getinfo-sensors
#
# This script polls information from smc(8) and outputs the polled
# information in a format usable by mrtg. It can also function as a required
# file, in which case it will gather the data from sensors(1) but not output
# anything to stdout.

use strict;
use integer;

use Getopt::Long;

use POSIX;
use Unix::Uptime;

use vars qw( @sensorsflags );
use vars qw( $verbose_p );

# See if we are being require'd from another perl5 program.
# If we are, we expect caller(0) to return non-null information;
# in particular, $subroutine should be "(eval)" (by empirical observation).

my($package, $filename, $line, $subroutine, $hasargs, $wantargs) = caller(0);
if (! defined $subroutine) {
   GetOptions(
      'debug' => sub { @sensorsflags = qw(-c /etc/sensors.new) },
      'verbose|v' => \$verbose_p,
   ) || exit(1);
}

sub read_sensor ($) {
   my($key) = @_;
   my $pid = open(SENSORS, '-|');
   die "fork: $!\n" unless defined $pid;
   if (!$pid) {
      my $sensors = '/usr/local/sbin/smc';
      my @cmd = ($sensors, '-k', $key, '-r');
      printf STDERR "%u#\t%s\n", time, "@cmd" if $verbose_p;
      exec {$sensors} @cmd;
      die "$sensors: exec: $!\n";
   }
   my $data = scalar <SENSORS>;
   close SENSORS;
   my $it;
   if ($data =~ /$key  \[....\]  (\d+) \(.*\)/) {
      $it = $1;
   } elsif ($data =~ /(?=T)$key  \[sp78\]  \(bytes (.*)\)/) {
      my @bytes = map { hex($_) } split(/ /, $1);
      no integer;
      $it = $bytes[0] + $bytes[1]/256.0 if $bytes[0] && $bytes[0] != 0xff;
   } elsif ($data =~ /no data/) {
      $it = undef;
   }
   return $it;
}

sub write_sensor ($$$) {
   my($key, $type, $intval) = @_;
   my $pid = open(SENSORS, '|-');
   die "fork: $!\n" unless defined $pid;
   if (!$pid) {
      my $sensors = '/usr/local/sbin/smc';
      my $code;
      if ($type eq 'ui16') {
	 $code = sprintf "%04x", $intval;
      } elsif ($type eq 'sp78') {
	 $code = $intval << 2;
	 $code = sprintf "%04x", $code;
      } else {
	 die;
      }
      my @cmd = ($sensors, '-k', $key, '-w', $code);
      printf STDERR "%u#\t%s\n", time, "@cmd" if $verbose_p;
      exec {$sensors} @cmd;
      die "$sensors: exec: $!\n";
   }
   close SENSORS;
}

################################################################################

my $ack;

if (@ARGV == 0) {
   $ack = 1;
} elsif (@ARGV == 1) {
   my $setpoint = $ARGV[0];
   if ($setpoint !~ /^\d+$/) {
      die "Setpoint be a whole number\n";
   } elsif ($setpoint < 2000) {
      die "Setpoint too low\n";
   } elsif ($setpoint > 6200) {
      die "Setpoint too high\n";
   } else {
      write_sensor('FS! ', 'ui16', 1);
      write_sensor('F0Tg', 'sp78', $setpoint);
      $ack = $verbose_p;
   }
}
if ($ack) {
   my $curr_speed = read_sensor('F0Ac');
   my $curr_setpoint = read_sensor('F0Tg');
   printf "Fan speed: %d, setpoint: %d\n", $curr_speed, $curr_setpoint;
}
