#!/bin/sh

PATH="$PATH:/usr/local/sbin"
HIBERNATE=25

fanspeed="`fanspeed --target`"
fanspeed 6200

hibernatemode="`pmset -g|grep hibernatemode|awk '{print $2}'`"
echo "Temporarily switching hibernate mode from $hibernatemode to $HIBERNATE..."
pmset -a hibernatemode $HIBERNATE

# Make sure we don't wake the Mac by accident. The acwake parameter is
# especially dangerous, but so is lidwake if what the Apple techs say is true.
# Alas, the Power Manager does not seem to actually honour these values :-/
pmset -a lidwake 0
pmset -a acwake 0

echo "Syncing disks..."
sync; sync; sync
sleep 5

# Apparently, standby must be 0 for lidwake and acwake to work (?!)
echo "Going into hibernation..."
pmset -a hibernatemode $HIBERNATE force
pmset -a standby 0
pmset -a lidwake 0 force
pmset -a acwake 0 force
pmset sleepnow

# pmset sleepnow will immediately return before the system goes to hibernation
# so we must insert a delay here to compensate
# Otherwise we will change the hibernate mode back before the system even
# goes into hibernation.

echo Wait...
sleep 5

hibernatemode_chk="`pmset -g|grep hibernatemode|awk '{print $2}'`"
if [ "x$hibernatemode_chk" != "x$hibernatemode" ]; then
	echo "Restoring hibernation mode to $hibernatemode"
	pmset -a hibernatemode "$hibernatemode"
fi

fanspeed_chk="`fanspeed --target`"
if [ "x$fanspeed_chk" != "x$fanspeed" ]; then
	echo "Restoring fan speed to $fanspeed"
	fanspeed $fanspeed
fi
