#!/bin/sh

PATH="$PATH:/usr/local/sbin"
HIBERNATE=25

fanspeed="`fanspeed --target`"
fanspeed 6200

hibernatemode="`pmset -g|grep hibernatemode|awk '{print $2}'`"
echo "Temporarily switching hibernate mode from $hibernatemode to $HIBERNATE..."
pmset -a hibernatemode $HIBERNATE force

echo "Syncing disks..."
sync; sync; sync

echo "Going into hibernation..."
pmset sleepnow

hibernatemode_chk="`pmset -g|grep hibernatemode|awk '{print $2}'`"
if [ "x$hibernatemode_chk" != "x$hibernatemode" ]; then
	echo "Restoring hibernation mode to $hibernatemode"
	pmset -a hibernatemode "$hibernatemode"
fi

fanspeed_chk="`fanspeed --target`"
if [ "x$fanspeed_chk" != "x$fanspeed" ]; then
	echo "Restoring fan speed to $fanspeed"
	fanspeed $fanspeed
fi
